name: 'amazon_ads'
version: '0.5.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  amazon_ads:
    +schema: amazon_ads
    +materialized: table
    intermediate:
      +materialized: view
vars:
  amazon_ads:    
    sb_campaign_history: "{{ ref('amazon_ads_sb_campaign_history') }}"
    sb_ad_report: "{{ ref('amazon_ads_sb_ad_report') }}"
    ad_group_history: "{{ ref('amazon_ads_ad_group_history') }}"
    ad_group_level_report: "{{ ref('amazon_ads_ad_group_level_report') }}"
    advertised_product_report: "{{ ref('amazon_ads_advertised_product_report') }}"
    campaign_history: "{{ ref('amazon_ads_campaign_history') }}"
    campaign_level_report: "{{ ref('amazon_ads_campaign_level_report') }}"
    portfolio_history: "{{ ref('amazon_ads_portfolio_history') }}"
    product_ad_history: "{{ ref('amazon_ads_product_ad_history') }}"
    profile: "{{ ref('amazon_ads_profile') }}"
    keyword_history: "{{ ref('amazon_ads_keyword_history') }}"
    targeting_keyword_report: "{{ ref('amazon_ads_targeting_keyword_report') }}"
    search_term_ad_keyword_report: "{{ ref('amazon_ads_search_term_ad_keyword_report') }}"
