name: 'amazon_ads'
version: '0.5.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  
  amazon_ads:
    +materialized: table
    intermediate:
      +materialized: view
vars:
  amazon_ads:    
    sb_campaign_history: "{{ source('amazon_ads', 'sb_campaign_history') }}"
    sb_ad_report: "{{ source('amazon_ads', 'sb_ad_report') }}"
    ad_group_history: "{{ source('amazon_ads', 'ad_group_history') }}"
    ad_group_level_report: "{{ source('amazon_ads', 'ad_group_level_report') }}"
    advertised_product_report: "{{ source('amazon_ads', 'advertised_product_report') }}"
    campaign_history: "{{ source('amazon_ads', 'campaign_history') }}"
    campaign_level_report: "{{ source('amazon_ads', 'campaign_level_report') }}"
    portfolio_history: "{{ source('amazon_ads', 'portfolio_history') }}"
    product_ad_history: "{{ source('amazon_ads', 'product_ad_history') }}"
    profile: "{{ source('amazon_ads', 'profile') }}"
    keyword_history: "{{ source('amazon_ads', 'keyword_history') }}"
    targeting_keyword_report: "{{ source('amazon_ads', 'targeting_keyword_report') }}"
    search_term_ad_keyword_report: "{{ source('amazon_ads', 'search_term_ad_keyword_report') }}"

